services:
  postgres:
    image: postgres:16
    container_name: hoteloccupancy_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - hotel_data:/var/lib/postgresql/data
volumes:
  hotel_data:
